<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseLibrary.Idp.Domain\CourseLibrary.Idp.Domain.csproj" />
    <ProjectReference Include="..\CourseLibrary.Idp.Application\CourseLibrary.Idp.Application.csproj" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="OpenIddict.Abstractions" Version="7.6.0" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.8.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.9.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Compliance.Redaction" Version="10.8.0" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Resilience" Version="10.8.0" />
    <PackageReference Include="OpenTelemetry" Version="1.17.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.17.0" />
  </ItemGroup>

</Project>
