<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CourseLibrary.Application\CourseLibrary.Application.csproj" />
		<ProjectReference Include="..\CourseLibrary.Domain\CourseLibrary.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" Version="1.5.4" />
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
		<PackageReference Include="MessagePack" Version="3.1.8" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OutputCaching.StackExchangeRedis" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.9.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
		<PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.9.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Compliance.Redaction" Version="10.9.0" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Resilience" Version="10.9.0" />
		<PackageReference Include="OpenTelemetry" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Api" Version="1.18.0" />
		<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="ZiggyCreatures.FusionCache" Version="2.7.2" />
		<PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" Version="2.7.2" />
		<PackageReference Include="ZiggyCreatures.FusionCache.Serialization.NeueccMessagePack" Version="2.7.2" />
		<PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" Version="2.7.2" />
	</ItemGroup>
</Project>
